#   base dc=example,dc=org, users under ou=users,
#   seeded users user01/password1 and user02/password2.
ldap.host     = "localhost"
ldap.host     = ${?LDAP_HOST}
ldap.port     = 389
ldap.port     = ${?LDAP_PORT}
ldap.startTls = false
ldap.startTls = ${?LDAP_START_TLS}
ldap.useSsl   = false
ldap.useSsl   = ${?LDAP_USE_SSL}
ldap.name     = "cn=%USER%,%USER_ROOT%"
ldap.name     = ${?LDAP_NAME}
ldap.userRoot = "ou=users,dc=example,dc=org"
ldap.userRoot = ${?LDAP_USER_ROOT}
