mongodb_cluster = {
    serverName        = "localhost"
    serverName        = ${?MONGODB_CLUSTER_HOSTNAME}
    portNumber        = "27017"
    portNumber        = ${?MONGODB_CLUSTER_PORT}
    databaseName      = "admin"
    databaseName      = ${?MONGODB_CLUSTER_DATABASE}
    username          = "root"
    username          = ${?MONGODB_CLUSTER_USER}
    password          = "toor"
    password          = ${?MONGODB_CLUSTER_PASSWORD}
    initialCollection = "initial"
    tls               = "false"
    tls               = ${?MONGODB_CLUSTER_TLS}
}
