pg_cluster {
    dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
    properties = {
        serverName = "postgres.f4.htw-berlin.de"
        portNumber = "5432"
        databaseName = "internal"
        user = "postgres"
        password = "oAReYbQBAAKTrFEtwMQn"
    }
}

# Postgres will split the authentication mechanism according to the role
ldap_role = "ldap_role"
generic_role = "generic_role"