pg_cluster {
    dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
    properties = {
        serverName   = "localhost"
        serverName   = ${?PG_CLUSTER_HOSTNAME}
        portNumber   = "5555"
        portNumber   = ${?PG_CLUSTER_PORT}
        databaseName = "internal"
        databaseName = ${?PG_CLUSTER_DATABASE}
        user         = "postgres"
        user         = ${?PG_CLUSTER_USER}
        password     = "postgres"
        password     = ${?PG_CLUSTER_PASSWORD}
    }
}

# Postgres splits the authentication mechanism by role.
ldap_role    = "ldap_role"
generic_role = "generic_role"
