# https://www.playframework.com/documentation/latest/PlaySlick
slick.dbs.default.profile     = "slick.jdbc.PostgresProfile$"
slick.dbs.default.db.driver   = "org.postgresql.Driver"
slick.dbs.default.db.url      = "jdbc:postgresql://localhost:5432/internal"
slick.dbs.default.db.url      = ${?SLICK_DB_URL}
slick.dbs.default.db.user     = "postgres"
slick.dbs.default.db.user     = ${?SLICK_DB_USER}
slick.dbs.default.db.password = "postgres"
slick.dbs.default.db.password = ${?SLICK_DB_PASSWORD}

# https://www.playframework.com/documentation/latest/Evolutions
play.evolutions.autoApply                 = true
play.evolutions.db.default.autoApply      = true
play.evolutions.db.default.autoApplyDowns = true
