name: ocean-dev

services:
  openldap:
    image: bitnamilegacy/openldap:2
    environment:
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: adminpassword
      LDAP_USERS: user01,user02
      LDAP_PASSWORDS: password1,password2
    ports:
      - "1389:1389"
      - "1636:1636"

  postgres_orm:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: internal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_orm_data:/var/lib/postgresql/data

  pg_cluster:
    image: postgres:12.20
    environment:
      POSTGRES_DB: internal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5555:5432"
    volumes:
      - pg_cluster_data:/var/lib/postgresql/data

  mongodb_cluster:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - "27017:27017"
    volumes:
      - mongodb_cluster_data:/data/db

  adminer:
    image: adminer:5
    depends_on:
      - postgres_orm
      - pg_cluster
    ports:
      - "8080:8080"

  backend:
    profiles: ["full"]
    build:
      context: ./backend
    image: ocean-backend:dev
    env_file: .env
    depends_on:
      - postgres_orm
      - pg_cluster
      - mongodb_cluster
      - openldap
    ports:
      - "9000:9000"

  frontend:
    profiles: ["full"]
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL:-/v1}
        VITE_POSTGRESQL_HOSTNAME: ${VITE_POSTGRESQL_HOSTNAME:-localhost}
        VITE_POSTGRESQL_PORT: ${VITE_POSTGRESQL_PORT:-5555}
        VITE_MONGODB_HOSTNAME: ${VITE_MONGODB_HOSTNAME:-localhost}
        VITE_MONGODB_PORT: ${VITE_MONGODB_PORT:-27017}
        VITE_ADMINER_URL: ${VITE_ADMINER_URL:-http://localhost:8080/}
        VITE_ISSUE_LINK: ${VITE_ISSUE_LINK:-https://github.com/HTWHub/ocean/issues}
    image: ocean-frontend:dev
    depends_on:
      - backend
    ports:
      - "5193:80"

volumes:
  postgres_orm_data:
  pg_cluster_data:
  mongodb_cluster_data:
