name: ocean-mongo

services:
  mongodb_cluster:
    image: mongo:5
    restart: unless-stopped
    env_file: /etc/ocean/mongodb_cluster.env
    ports:
      - "27017:27017"
    volumes:
      - /srv/ocean/mongodb_cluster/data:/data/db
