name: ocean-pg

services:
  pg_cluster:
    image: postgres:12.20
    restart: unless-stopped
    env_file: /etc/ocean/pg_cluster.env
    ports:
      - "5432:5432"
    volumes:
      - /srv/ocean/pg_cluster/data:/var/lib/postgresql/data
      - /etc/ocean/tls:/etc/ssl/ocean:ro
      - /etc/ocean/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    command: >-
      postgres
      -c ssl=on
      -c ssl_cert_file=/etc/ssl/ocean/cert.pem
      -c ssl_key_file=/etc/ssl/ocean/key.pem
      -c hba_file=/etc/postgresql/pg_hba.conf

  adminer:
    image: adminer:5
    restart: unless-stopped
    command: ["php", "-S", "0.0.0.0:8080", "-t", "/var/www/html"] #bind to ipV4
    environment:
      ADMINER_DEFAULT_SERVER: pg_cluster:5432
      PGSSLMODE: disable
    depends_on:
      - pg_cluster

  adminer_proxy:
    image: caddy:2-alpine
    restart: unless-stopped
    depends_on:
      - adminer
    ports:
      - "443:443"
    volumes:
      - /etc/ocean/Caddyfile:/etc/caddy/Caddyfile:ro
      - /etc/ocean/tls:/etc/caddy/tls:ro
