all:
  vars:
    ansible_user: ansible
    ansible_python_interpreter: /usr/bin/python3
    # HTW outbound HTTP(S) only reachable via this proxy.
    outbound_proxy_url: http://webproxy.rz.htw-berlin.de:3128
    tls_src: "{{ playbook_dir }}/../certs"
  children:
    ops:
      hosts:
        ocean-ops:
          ansible_host: ocean-ops.f4.htw-berlin.de
    app:
      hosts:
        ocean-app:
          ansible_host: ocean-jg.f4.htw-berlin.de
          tls_cert_file: ocean-jg.pem
          tls_key_file: ocean-jg.f4.htw-berlin.de.key
          tls_key_uid: "{{ ocean_user }}"
    pg:
      hosts:
        ocean-pg:
          ansible_host: ocean-pg.f4.htw-berlin.de
          tls_cert_file: ocean-pg.pem
          tls_key_file: ocean-pg.f4.htw-berlin.de.key
          tls_key_uid: "999"   # postgres image runs as UID 999
    mongo:
      hosts:
        ocean-mongo:
          ansible_host: ocean-mongo.f4.htw-berlin.de
          tls_cert_file: ocean-mongo.pem
          tls_key_file: ocean-mongo.f4.htw-berlin.de.key
          tls_key_uid: "999"   # mongo image runs as UID 999
