- name: Base setup on all hosts
  hosts: all
  become: true
  roles:
    - base

- name: Stage TLS material on app/db hosts
  hosts: app:pg:mongo
  become: true
  roles:
    - tls
  tags: tls

- name: Provision pg-vm
  hosts: pg
  become: true
  roles:
    - pg

- name: Provision mongo-vm
  hosts: mongo
  become: true
  roles:
    - mongo

- name: Provision app-vm
  hosts: app
  become: true
  roles:
    - app

- name: Provision GitLab runner VM
  hosts: ops
  become: true
  roles:
    - gitlab-runner
